// Copyright (c) Asymptotic Labs
// SPDX-License-Identifier: Apache-2.0

//! Equation / projection lemmas for impl defs under the per-MODULE
//! `irreducible_defs` gate (unified-backend design §5.3, Phase 3.2).
//!
//! For every eligible def in a gated module the pass computes an
//! [`EquationLemmaSet`]; the renderer then (a) suppresses the `@[reducible]`
//! attribute on the def, (b) emits the lemma block right after it —
//! `<fn>.eq_body` (whole body, `rfl`), `<fn>.eq_then` / `<fn>.eq_else`
//! (terminal-`if` branch equations, proven via `SpecEnsures.ite_then/_else`),
//! `<fn>.result_<k>` (tuple-component projections, `rfl`) — and (c) emits
//! `attribute [irreducible] <fn>` AFTER the block, so the lemmas elaborate
//! at default transparency while every downstream tactic that tries
//! `simp [<fn>]` / `unfold <fn>` fails fast instead of hitting the whnf wall.
//!
//! Lemma statements use the same let-substitution + projection-folding
//! discipline as the obligation bundles (`bundle_subst`), so they are closed
//! over the def's own parameters. Naming deviates from the design doc's
//! `F.eq_1…F.eq_b` because Lean reserves the autogenerated
//! `<fn>.eq_<n>`/`<fn>.eq_def` equation-lemma names.

use crate::data::types::{TempId, Type};
use crate::data::EquationLemmaSet;
use crate::{IRNode, Program};
use std::collections::BTreeMap;

/// Cap on any single substituted lemma statement (mirrors the bundle walk).
const SUBST_MAX: usize = 6_000;
/// Whole-body `eq_body` lemmas are suppressed above this size (the doc's
/// "kept small by the existing segmentation" — oversized bodies get only the
/// branch/projection surface).
const UNFOLD_MAX: usize = 12_000;

/// The per-MODULE `irreducible_defs` gate: a scanned
/// `def <Module>.module_options` hook listing `"irreducible_defs"` whose stem
/// names this module (case-insensitively — hook stems are Lean namespaces,
/// `Module::name` is the Move module name).
pub fn irreducible_defs_enabled(program: &Program, module_id: crate::ModuleID) -> bool {
    let module_name = &program.modules.get(module_id).name;
    program
        .lean_termination_decls
        .module_options
        .iter()
        .any(|(stem, opts)| {
            opts.contains("irreducible_defs") && stem.eq_ignore_ascii_case(module_name)
        })
}

pub fn compute_equation_lemmas(program: &mut Program) {
    let gated: Vec<crate::ModuleID> = program
        .modules
        .iter_ids()
        .filter(|mid| irreducible_defs_enabled(program, *mid))
        .collect();
    if gated.is_empty() {
        return;
    }
    let candidates: Vec<crate::FunctionID> = program
        .functions
        .iter_ids()
        .filter(|id| {
            let f = program.functions.get(id);
            gated.contains(&f.module_id) && eligible(program, f)
        })
        .collect();
    for id in candidates {
        let f = program.functions.get(&id);
        let (unfold, branches, projections) = analyze(program, f);
        if !unfold && branches.is_none() && projections.is_empty() {
            continue;
        }
        program.equation_lemmas.push(EquationLemmaSet {
            fn_id: id,
            unfold,
            branches,
            projections,
        });
    }
}

/// The `@[reducible]` impl-def class, minus everything whose elaboration
/// relies on staying unfoldable (`.aborts` bundle theorems, segments, atoms,
/// obligation defs) or whose rendering is position-sensitive (proof-param
/// placeholders, accessor implicit-param specials, mutable-reference state).
fn eligible(program: &Program, f: &crate::Function) -> bool {
    if f.is_native
        || f.theorem.is_some()
        || f.mutual_group_id.is_some()
        || !f.signature.type_params.is_empty()
        || !f.signature.proof_params.is_empty()
        || f.signature.return_type == Type::Prop
    {
        return false;
    }
    if matches!(&f.body, IRNode::Tuple(v) if v.is_empty()) {
        return false;
    }
    let n = &f.name;
    if n.contains(".aborts")
        || n.contains(".requires")
        || n.contains(".ensures")
        || n.contains(".asserts")
        || n.contains(".atom_")
        || n.contains(".seg_")
        || n.contains(".while_")
        || n.contains(".after")
    {
        return false;
    }
    if f.is_field_accessor().is_some() {
        return false;
    }
    if f.signature.parameters.iter().any(|p| {
        matches!(
            p.param_type,
            Type::MutableReference(_, _) | Type::Reference(_)
        )
    }) || matches!(f.signature.return_type, Type::MutableReference(_, _))
    {
        return false;
    }
    if f.body.iter().any(|n| {
        matches!(
            n,
            IRNode::Abort { .. } | IRNode::Inhabited | IRNode::MutableCompose { .. }
        )
    }) {
        return false;
    }
    // Verbatim-proof-param callees force entry-macro / `sorry` render forms
    // inside the statement copy; keep those bodies def-only.
    if f.body.iter().any(|n| {
        matches!(n, IRNode::Call { function, .. }
            if !program.functions.get(function).signature.proof_params.is_empty())
    }) {
        return false;
    }
    true
}

type Subst = BTreeMap<TempId, Option<IRNode>>;

/// Walk the top-level `Let` spine building the parent-param substitution,
/// then derive branch / projection lemma expressions from the terminal.
fn analyze(
    program: &Program,
    f: &crate::Function,
) -> (bool, Option<(IRNode, IRNode, IRNode)>, Vec<(usize, IRNode)>) {
    let unfold = super::decompose_aborts::approx_size(&f.body) <= UNFOLD_MAX;

    let mut subst: Subst = BTreeMap::new();
    let mut cur = &f.body;
    let mut poisoned = false;
    loop {
        match cur {
            IRNode::Let {
                pattern,
                value,
                body,
            } => {
                if pattern.len() == 1 {
                    let sub = super::decompose_aborts::bundle_subst(value, &subst)
                        .filter(|e| super::decompose_aborts::approx_size(e) <= SUBST_MAX);
                    if sub.is_none() {
                        poisoned = true;
                    }
                    subst.insert(pattern[0].clone(), sub);
                } else if !pattern.is_empty() {
                    match super::decompose_aborts::bundle_subst(value, &subst)
                        .filter(|e| super::decompose_aborts::approx_size(e) <= SUBST_MAX)
                    {
                        Some(ve) => {
                            for p in pattern.iter() {
                                subst.insert(
                                    p.clone(),
                                    Some(IRNode::Let {
                                        pattern: pattern.clone(),
                                        value: Box::new(ve.clone()),
                                        body: Box::new(IRNode::Var(p.clone())),
                                    }),
                                );
                            }
                        }
                        None => {
                            poisoned = true;
                            for p in pattern.iter() {
                                subst.insert(p.clone(), None);
                            }
                        }
                    }
                }
                cur = body;
            }
            terminal => {
                let mut branches = None;
                let mut projections = Vec::new();
                if !poisoned {
                    match terminal {
                        IRNode::If {
                            cond,
                            then_branch,
                            else_branch,
                        } => {
                            let ok = |e: &IRNode| {
                                super::decompose_aborts::bundle_subst(e, &subst).filter(|s| {
                                    super::decompose_aborts::approx_size(s) <= SUBST_MAX
                                })
                            };
                            if let (Some(c), Some(t), Some(e)) =
                                (ok(cond), ok(then_branch), ok(else_branch))
                            {
                                branches = Some((c, t, e));
                            }
                        }
                        IRNode::Tuple(elems) if elems.len() >= 2 => {
                            let subbed: Option<Vec<IRNode>> = elems
                                .iter()
                                .map(|e| {
                                    super::decompose_aborts::bundle_subst(e, &subst).filter(|s| {
                                        super::decompose_aborts::approx_size(s) <= SUBST_MAX
                                    })
                                })
                                .collect();
                            if let Some(subbed) = subbed {
                                projections = subbed.into_iter().enumerate().collect();
                            }
                        }
                        _ => {}
                    }
                }
                let _ = program;
                return (unfold, branches, projections);
            }
        }
    }
}

/// Whether the renderer must suppress `@[reducible]` and emit the
/// `attribute [irreducible]` line for this function.
pub fn is_irreducible_def(program: &Program, fn_id: crate::FunctionID) -> bool {
    program.equation_lemmas.iter().any(|s| s.fn_id == fn_id)
}
