-- Correctness proof obligations generated by the translator.
import lean_demo.Math
import lean_demo.Math
import Proofs.MathProofs

namespace Math

theorem clamp_spec.aborts_proved (value : BoundedNat (2^64)) (low : BoundedNat (2^64)) (high : BoundedNat (2^64)) :
    clamp_spec.requires value low high →
    Math.clamp.aborts value low high = Option.none :=
  Math_proofs.clamp_spec_aborts value low high

theorem clamp_spec.ensures_proved (value : BoundedNat (2^64)) (low : BoundedNat (2^64)) (high : BoundedNat (2^64)) :
    clamp_spec.requires value low high →
    clamp_spec.ensures value low high :=
  Math_proofs.clamp_spec_ensures value low high

theorem clamp_spec.ensures_1_proved (value : BoundedNat (2^64)) (low : BoundedNat (2^64)) (high : BoundedNat (2^64)) :
    clamp_spec.requires value low high →
    clamp_spec.ensures_1 value low high :=
  Math_proofs.clamp_spec_ensures_1 value low high

theorem clamp_spec.ensures_2_proved (value : BoundedNat (2^64)) (low : BoundedNat (2^64)) (high : BoundedNat (2^64)) :
    clamp_spec.requires value low high →
    clamp_spec.ensures_2 value low high :=
  Math_proofs.clamp_spec_ensures_2 value low high

theorem clamp_spec.requires_proved (value : BoundedNat (2^64)) (low : BoundedNat (2^64)) (high : BoundedNat (2^64)) :
    clamp_spec.requires value low high →
    clamp_spec.requires value low high :=
  Math_proofs.clamp_spec_requires value low high

theorem distance_spec.aborts_proved (a : BoundedNat (2^64)) (b : BoundedNat (2^64)) :
    distance_spec.aborts a b = Option.none :=
  Math_proofs.distance_spec_aborts a b

theorem distance_spec.ensures_proved (a : BoundedNat (2^64)) (b : BoundedNat (2^64)) :
    distance_spec.ensures a b :=
  Math_proofs.distance_spec_ensures a b

theorem distance_spec.ensures_1_proved (a : BoundedNat (2^64)) (b : BoundedNat (2^64)) :
    distance_spec.ensures_1 a b :=
  Math_proofs.distance_spec_ensures_1 a b

theorem distance_spec.ensures_2_proved (a : BoundedNat (2^64)) (b : BoundedNat (2^64)) :
    distance_spec.ensures_2 a b :=
  Math_proofs.distance_spec_ensures_2 a b

theorem max_spec.aborts_proved (a : BoundedNat (2^64)) (b : BoundedNat (2^64)) :
    max_spec.aborts a b = Option.none :=
  Math_proofs.max_spec_aborts a b

theorem max_spec.ensures_proved (a : BoundedNat (2^64)) (b : BoundedNat (2^64)) :
    max_spec.ensures a b :=
  Math_proofs.max_spec_ensures a b

theorem max_spec.ensures_1_proved (a : BoundedNat (2^64)) (b : BoundedNat (2^64)) :
    max_spec.ensures_1 a b :=
  Math_proofs.max_spec_ensures_1 a b

theorem max_spec.ensures_2_proved (a : BoundedNat (2^64)) (b : BoundedNat (2^64)) :
    max_spec.ensures_2 a b :=
  Math_proofs.max_spec_ensures_2 a b

theorem transfer_spec.aborts_proved (from_ : Balance) (to : Balance) (amount : BoundedNat (2^64)) :
    transfer_spec.asserts_cond from_ to amount →
    transfer_spec.asserts_cond_1 from_ to amount →
    Math.transfer.aborts from_ to amount = Option.none :=
  Math_proofs.transfer_spec_aborts from_ to amount

theorem transfer_spec.ensures_proved (from_ : Balance) (to : Balance) (amount : BoundedNat (2^64)) :
    transfer_spec.asserts_cond from_ to amount →
    transfer_spec.asserts_cond_1 from_ to amount →
    transfer_spec.ensures from_ to amount :=
  Math_proofs.transfer_spec_ensures from_ to amount

theorem transfer_spec.ensures_1_proved (from_ : Balance) (to : Balance) (amount : BoundedNat (2^64)) :
    transfer_spec.asserts_cond from_ to amount →
    transfer_spec.asserts_cond_1 from_ to amount →
    transfer_spec.ensures_1 from_ to amount :=
  Math_proofs.transfer_spec_ensures_1 from_ to amount

theorem transfer_spec.ensures_2_proved (from_ : Balance) (to : Balance) (amount : BoundedNat (2^64)) :
    transfer_spec.asserts_cond from_ to amount →
    transfer_spec.asserts_cond_1 from_ to amount →
    transfer_spec.ensures_2 from_ to amount :=
  Math_proofs.transfer_spec_ensures_2 from_ to amount

theorem withdraw_spec.aborts_proved (balance : Balance) (amount : BoundedNat (2^64)) :
    withdraw_spec.asserts_cond balance amount →
    Math.withdraw.aborts balance amount = Option.none :=
  Math_proofs.withdraw_spec_aborts balance amount

theorem withdraw_spec.ensures_proved (balance : Balance) (amount : BoundedNat (2^64)) :
    withdraw_spec.asserts_cond balance amount →
    withdraw_spec.ensures balance amount :=
  Math_proofs.withdraw_spec_ensures balance amount

theorem withdraw_spec.ensures_1_proved (balance : Balance) (amount : BoundedNat (2^64)) :
    withdraw_spec.asserts_cond balance amount →
    withdraw_spec.ensures_1 balance amount :=
  Math_proofs.withdraw_spec_ensures_1 balance amount

end Math
